### ISSUE TITLE
Plugin shuts off after unrelated lichess tab is closed

### ISSUE THREAD

**Issue by lk-kit** [kieferro/Lichess-Functions#19]
Was playing in one tab, closed an unrelated lichess tab which made the ratings reappear.

**Comment by kieferro** [comment]
This happens when you hover over the four items at the top right

**Comment by kieferro** [comment]
The problem is that when hovering over the button at the very top right, an object of the class "status" is created with the name of the player. This object is linked to the lag display in the context menu.
As a result, however, the plugin thinks that the game is over and displays the ratings.
